# Lesson 9.01 Introduction to Neural Networks

## Objective
- Build and execute a neural network with a Perceptron 

## Perceptron Overview
- It is a neural network with just one layer
- It is a linear classifier that outputs a binary response variable
- This model is also called a "linear binary classifier"
- Data must be linearly separable in order for a perceptron to operate properly where it can be cleanly classified into one of two classes

## Elements of a Perceptron
- Input layer refers to the input variables
- Weights refer to the co-efficients of the equation which you are trying to resolve.
    - Negative weights reduce the value of an output.
- Bias refers to a constant value (or a constant vector) that is added to the product of inputs and weights.
- Weighted Sum refers to the sum of (weight * input) for all observations + bias
- Activation Function refers to a mathematical function that can normalise the input variables
    - Enables NNs to model complex / non-linear phenomenon

In [1]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

from sklearn.linear_model import Perceptron

In [2]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

# Print first 10 rows of X-values
X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
standardize = StandardScaler()

# We use fit_transform() on the train data so that we learn the parameters of scaling on the train data
# in the same time we scale the train data.
standardized_X_train = standardize.fit_transform(X_train)

# We only use transform() on the test data because we use the scaling paramaters previously learned on the train data
# to scale the test data.
standardized_X_test = standardize.transform(X_test)

In [5]:
# Print first 10 rows of scaled X-values
standardized_X_test[0:10,]

array([[ 0.35451684, -0.58505976,  0.55777524,  0.02224751],
       [-0.13307079,  1.65083742, -1.16139502, -1.17911778],
       [ 2.30486738, -1.0322392 ,  1.8185001 ,  1.49058286],
       [ 0.23261993, -0.36147005,  0.44316389,  0.4227026 ],
       [ 1.2077952 , -0.58505976,  0.61508092,  0.28921757],
       [-0.49876152,  0.75647855, -1.27600637, -1.04563275],
       [-0.2549677 , -0.36147005, -0.07258719,  0.15573254],
       [ 1.32969211,  0.08570939,  0.78699794,  1.49058286],
       [ 0.47641375, -1.92659808,  0.44316389,  0.4227026 ],
       [-0.01117388, -0.80864948,  0.09932984,  0.02224751]])

In [6]:
# Instantiate a Perceptron object
perceptron = Perceptron(random_state=42)

# y_train data needs to be supplied as a 1-d array into the model
perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(random_state=42)

In [7]:
y_pred = perceptron.predict(standardized_X_test)

In [8]:
print(y_test)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [9]:
print(y_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 1 0 2 2 2 1 2 0 0]


In [10]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.82      1.00      0.90         9
           2       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.93        30
weighted avg       0.95      0.93      0.93        30

